package com.mb.memp.persistence.mapper;

import java.util.List;
import com.mb.common.dal.BaseMapper;
import org.springframework.stereotype.Repository;
import com.mb.memp.persistence.beans.PmHplRoleInfo;

/**
 * 角色信息表。Mapper
 * @author fyn
 * @date 2016-08-02
 * @source Generated by MySQL2Java
 */
@Repository
public interface PmHplRoleInfoMapper extends BaseMapper<PmHplRoleInfo, Integer> {

    /**
     * 获取角色信息。
     * @param pmHplRoleInfo
     * @return List<PmHplRoleInfo>
     */
    public List<PmHplRoleInfo> getPmHplRoleInfo(PmHplRoleInfo pmHplRoleInfo);

    /**
     * 添加角色信息。
     * @param pmHplRoleInfo
     */
    public void addPmHplRoleInfo(PmHplRoleInfo pmHplRoleInfo);

    /**
     * 修改角色信息。
     * @param pmHplRoleInfo
     */
    public void editPmHplRoleInfo(PmHplRoleInfo pmHplRoleInfo);

    /**
     * 作废角色信息。
     * @param pmHplRoleInfo
     */
    public void delPmHplRoleInfo(PmHplRoleInfo pmHplRoleInfo);

}
