package com.fyn.sys.beans;

import com.fyn.common.dal.object.AbstractDO;

/**
 * 角色表模型
 * @author fyn
 * @date 2016-06-06
 * @source Generated by MySQL2Java
 */
public class SysRoleInfo extends AbstractDO {

    /**
     * 角色ID
     */
    private int roleId;

    /**
     * 角色名称
     */
    private String roleName;

    /**
     * 取值 角色ID
     * @return 角色ID
     */
    public int getRoleId() {
        return this.roleId;
    }

    /**
     * 赋值 角色ID
     * @param roleId 角色ID
     */
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    /**
     * 取值 角色名称
     * @return 角色名称
     */
    public String getRoleName() {
        return this.roleName;
    }

    /**
     * 赋值 角色名称
     * @param roleName 角色名称
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

}
