package com.fyn.sys.beans;

import com.fyn.common.dal.object.AbstractDO;

/**
 * 角色菜单表模型
 * @author fyn
 * @date 2016-06-06
 * @source Generated by MySQL2Java
 */
public class SysRoleMenu extends AbstractDO {

    /**
     * 角色ID
     */
    private int roleId;

    /**
     * 菜单ID
     */
    private int menuId;

    /**
     * 取值 角色ID
     * @return 角色ID
     */
    public int getRoleId() {
        return this.roleId;
    }

    /**
     * 赋值 角色ID
     * @param roleId 角色ID
     */
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

    /**
     * 取值 菜单ID
     * @return 菜单ID
     */
    public int getMenuId() {
        return this.menuId;
    }

    /**
     * 赋值 菜单ID
     * @param menuId 菜单ID
     */
    public void setMenuId(int menuId) {
        this.menuId = menuId;
    }

}
