package com.fyn.sys.beans;

import com.fyn.common.dal.object.AbstractDO;

/**
 * 用户表模型
 * @author fyn
 * @date 2016-06-06
 * @source Generated by MySQL2Java
 */
public class SysUserInfo extends AbstractDO {

    /**
     * 用户ID
     */
    private int userId;

    /**
     * 用户uuid，与老平台相同
     */
    private String userUuid;

    /**
     * 用户名
     */
    private String userName;

    /**
     * 手机号
     */
    private String mobileNo;

    /**
     * 密码
     */
    private String passwd;

    /**
     * 密保邮箱
     */
    private String securityEmail;

    /**
     * 用户类型
     */
    private String userType;

    /**
     * 头像
     */
    private String headImg;

    /**
     * 昵称
     */
    private String nickName;

    /**
     * 登陆时间
     */
    private String loginTime;

    /**
     * 注册时间
     */
    private String regTime;

    /**
     * 性别
     */
    private String sex;

    /**
     * 姓名
     */
    private String realName;

    /**
     * 生日
     */
    private String birthday;

    /**
     * 取值 用户ID
     * @return 用户ID
     */
    public int getUserId() {
        return this.userId;
    }

    /**
     * 赋值 用户ID
     * @param userId 用户ID
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * 取值 用户uuid，与老平台相同
     * @return 用户uuid，与老平台相同
     */
    public String getUserUuid() {
        return this.userUuid;
    }

    /**
     * 赋值 用户uuid，与老平台相同
     * @param userUuid 用户uuid，与老平台相同
     */
    public void setUserUuid(String userUuid) {
        this.userUuid = userUuid;
    }

    /**
     * 取值 用户名
     * @return 用户名
     */
    public String getUserName() {
        return this.userName;
    }

    /**
     * 赋值 用户名
     * @param userName 用户名
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * 取值 手机号
     * @return 手机号
     */
    public String getMobileNo() {
        return this.mobileNo;
    }

    /**
     * 赋值 手机号
     * @param mobileNo 手机号
     */
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }

    /**
     * 取值 密码
     * @return 密码
     */
    public String getPasswd() {
        return this.passwd;
    }

    /**
     * 赋值 密码
     * @param passwd 密码
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * 取值 密保邮箱
     * @return 密保邮箱
     */
    public String getSecurityEmail() {
        return this.securityEmail;
    }

    /**
     * 赋值 密保邮箱
     * @param securityEmail 密保邮箱
     */
    public void setSecurityEmail(String securityEmail) {
        this.securityEmail = securityEmail;
    }

    /**
     * 取值 用户类型
     * @return 用户类型
     */
    public String getUserType() {
        return this.userType;
    }

    /**
     * 赋值 用户类型
     * @param userType 用户类型
     */
    public void setUserType(String userType) {
        this.userType = userType;
    }

    /**
     * 取值 头像
     * @return 头像
     */
    public String getHeadImg() {
        return this.headImg;
    }

    /**
     * 赋值 头像
     * @param headImg 头像
     */
    public void setHeadImg(String headImg) {
        this.headImg = headImg;
    }

    /**
     * 取值 昵称
     * @return 昵称
     */
    public String getNickName() {
        return this.nickName;
    }

    /**
     * 赋值 昵称
     * @param nickName 昵称
     */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /**
     * 取值 登陆时间
     * @return 登陆时间
     */
    public String getLoginTime() {
        return this.loginTime;
    }

    /**
     * 赋值 登陆时间
     * @param loginTime 登陆时间
     */
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * 取值 注册时间
     * @return 注册时间
     */
    public String getRegTime() {
        return this.regTime;
    }

    /**
     * 赋值 注册时间
     * @param regTime 注册时间
     */
    public void setRegTime(String regTime) {
        this.regTime = regTime;
    }

    /**
     * 取值 性别
     * @return 性别
     */
    public String getSex() {
        return this.sex;
    }

    /**
     * 赋值 性别
     * @param sex 性别
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * 取值 姓名
     * @return 姓名
     */
    public String getRealName() {
        return this.realName;
    }

    /**
     * 赋值 姓名
     * @param realName 姓名
     */
    public void setRealName(String realName) {
        this.realName = realName;
    }

    /**
     * 取值 生日
     * @return 生日
     */
    public String getBirthday() {
        return this.birthday;
    }

    /**
     * 赋值 生日
     * @param birthday 生日
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

}
