package com.fyn.sys.beans;

import com.fyn.common.dal.object.AbstractDO;

/**
 * 用户角色表模型
 * @author fyn
 * @date 2016-06-06
 * @source Generated by MySQL2Java
 */
public class SysUserRole extends AbstractDO {

    /**
     * 用户ID
     */
    private int userId;

    /**
     * 角色ID
     */
    private int roleId;

    /**
     * 取值 用户ID
     * @return 用户ID
     */
    public int getUserId() {
        return this.userId;
    }

    /**
     * 赋值 用户ID
     * @param userId 用户ID
     */
    public void setUserId(int userId) {
        this.userId = userId;
    }

    /**
     * 取值 角色ID
     * @return 角色ID
     */
    public int getRoleId() {
        return this.roleId;
    }

    /**
     * 赋值 角色ID
     * @param roleId 角色ID
     */
    public void setRoleId(int roleId) {
        this.roleId = roleId;
    }

}
