package com.fyn.sys.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import com.fyn.common.dal.BaseMapper;
import com.fyn.sys.beans.SysMenuInfo;
import com.fyn.sys.controller.vo.MenuTreeChildVO;
import com.fyn.sys.controller.vo.MenuTreeVO;
import com.fyn.sys.controller.vo.SysMenuInfoVO;

/**
 * 菜单表Mapper
 * @author fyn
 * @date 2016-06-06
 * @source Generated by MySQL2Java
 */
@Repository
public interface SysMenuInfoMapper extends BaseMapper<SysMenuInfo, Integer> {

    /**
     * 获取菜单
     * @param sysMenuInfo
     * @return List<SysMenuInfo>
     */
    public List<SysMenuInfo> getSysMenuInfo(SysMenuInfo sysMenuInfo);

    /**
     * 添加菜单
     * @param sysMenuInfo
     */
    public void addSysMenuInfo(SysMenuInfo sysMenuInfo);

    /**
     * 修改菜单
     * @param sysMenuInfo
     */
    public void editSysMenuInfo(SysMenuInfo sysMenuInfo);

    /**
     * 作废菜单
     * @param sysMenuInfo
     */
    public void delSysMenuInfo(SysMenuInfo sysMenuInfo);

    /**
     * 根据用户ID查询菜单列表
     * @param userId
     * @return
     */
	public List<SysMenuInfo> getMenuListByUserId(int userId);

	/**
	 * 根据用户ID查询父级菜单列表
	 * @param userId
	 * @return
	 */
    public List<SysMenuInfoVO> getPMenuListByUserId(int userId);

    /**
     * 根据父级ID查询菜单列表
     * @param getpMenuId
     * @return
     */
    public List<SysMenuInfo> getMenuListByPId(@Param("userId")int userId, @Param("pMenuId")int pMenuId);

    public List<SysMenuInfo> getSysMenuInfoList();

    public List<MenuTreeVO> getPMenuList();

    public List<MenuTreeChildVO> getCMenuList(String id);

}
