package com.fyn.sys.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.alibaba.dubbo.config.support.Parameter;
import com.fyn.common.dal.BaseMapper;
import com.fyn.sys.beans.SysRoleInfo;

/**
 * 角色表Mapper
 * @author fyn
 * @date 2016-06-06
 * @source Generated by MySQL2Java
 */
@Repository
public interface SysRoleInfoMapper extends BaseMapper<SysRoleInfo, Integer> {

    /**
     * 获取角色
     * @param sysRoleInfo
     * @return List<SysRoleInfo>
     */
    public List<SysRoleInfo> getSysRoleInfo(SysRoleInfo sysRoleInfo);

    /**
     * 添加角色
     * @param sysRoleInfo
     */
    public void addSysRoleInfo(SysRoleInfo sysRoleInfo);

    /**
     * 修改角色
     * @param sysRoleInfo
     */
    public void editSysRoleInfo(SysRoleInfo sysRoleInfo);

    /**
     * 作废角色
     * @param sysRoleInfo
     */
    public void delSysRoleInfo(SysRoleInfo sysRoleInfo);

    /**
     * 获取角色列表
     * @param param 
     * @return
     */
    public List<SysRoleInfo> getSysRoleInfoList(SysRoleInfo param);

    /**
     * 修改角色信息
     * @param role
     */
    public void updateSysRoleInfo(SysRoleInfo role);

    /**
     * 批量删除角色ID删除一个角色
     * @param ids
     */
    public void deleteSysRoleInfoById(@Param("ids")String[] ids);

    public Integer getIdByName(String roleName);

}
