package com.fyn.sys.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.fyn.common.dal.BaseMapper;
import com.fyn.sys.beans.SysRoleMenu;

/**
 * 角色菜单表Mapper
 * @author fyn
 * @date 2016-06-06
 * @source Generated by MySQL2Java
 */
@Repository
public interface SysRoleMenuMapper extends BaseMapper<SysRoleMenu, Integer> {

    /**
     * 获取角色菜单
     * @param sysRoleMenu
     * @return List<SysRoleMenu>
     */
    public List<SysRoleMenu> getSysRoleMenu(SysRoleMenu sysRoleMenu);

    /**
     * 添加角色菜单
     * @param sysRoleMenu
     */
    public void addSysRoleMenu(SysRoleMenu sysRoleMenu);

    /**
     * 修改角色菜单
     * @param sysRoleMenu
     */
    public void editSysRoleMenu(SysRoleMenu sysRoleMenu);

    /**
     * 作废角色菜单
     * @param sysRoleMenu
     */
    public void delSysRoleMenu(SysRoleMenu sysRoleMenu);

    public void deleteByRoleId(Integer roleId);

    public void addRoleMenuBatch(@Param("roleId")Integer roleId, @Param("menuId")String[] menuId);

}
