package com.fyn.sys.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;
import com.fyn.common.dal.BaseMapper;
import com.fyn.sys.beans.SysUserRole;

/**
 * 用户角色表Mapper
 * @author fyn
 * @date 2016-06-06
 * @source Generated by MySQL2Java
 */
@Repository
public interface SysUserRoleMapper extends BaseMapper<SysUserRole, Integer> {

    /**
     * 获取用户角色
     * @param sysUserRole
     * @return List<SysUserRole>
     */
    public List<SysUserRole> getSysUserRole(SysUserRole sysUserRole);

    /**
     * 添加用户角色
     * @param sysUserRole
     */
    public void addSysUserRole(SysUserRole sysUserRole);

    /**
     * 修改用户角色
     * @param sysUserRole
     */
    public void editSysUserRole(SysUserRole sysUserRole);

    /**
     * 作废用户角色
     * @param sysUserRole
     */
    public void delSysUserRole(SysUserRole sysUserRole);

}
