package com.fyn.sys.mapper;

import java.util.List;
import org.springframework.stereotype.Repository;
import com.fyn.common.dal.BaseMapper;
import com.fyn.sys.beans.SysUserInfo;

/**
 * 用户表Mapper
 * @author fyn
 * @date 2016-06-06
 * @source Generated by MySQL2Java
 */
@Repository
public interface SysUserInfoMapper extends BaseMapper<SysUserInfo, Integer> {

    /**
     * 获取用户
     * @param sysUserInfo
     * @return List<SysUserInfo>
     */
    public List<SysUserInfo> getSysUserInfo(SysUserInfo sysUserInfo);

    /**
     * 添加用户
     * @param sysUserInfo
     */
    public void addSysUserInfo(SysUserInfo sysUserInfo);

    /**
     * 修改用户
     * @param sysUserInfo
     */
    public void editSysUserInfo(SysUserInfo sysUserInfo);

    /**
     * 作废用户
     * @param sysUserInfo
     */
    public void delSysUserInfo(SysUserInfo sysUserInfo);

	public SysUserInfo getOneByNameAndPasswd(SysUserInfo sysUser);

    public List<SysUserInfo> getSysUserInfoList();

}
